sonar.projectKey=gitpins
sonar.projectName=GitPins
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src,tests
sonar.test.inclusions=tests/**/*.ts,src/**/*.test.ts,src/**/*.spec.ts

sonar.exclusions=src/generated/**,src/**/*.d.ts
sonar.coverage.exclusions=src/generated/**,src/**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
